services:
  nllb-serve:
    build: .
    ports:
      - "8123:6060"
    environment:
      - MODEL=facebook/nllb-200-distilled-600M
    volumes:
      - ./models:/root/.cache/huggingface
    restart: unless-stopped
